/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./components/common/AppDrawer.vue')['default']
    AppEmptyState: typeof import('./components/common/AppEmptyState.vue')['default']
    AppFooter: typeof import('./components/common/AppFooter.vue')['default']
    AppLazyImage: typeof import('./components/common/AppLazyImage.vue')['default']
    AppNavbar: typeof import('./components/common/AppNavbar.vue')['default']
    AppSkeletonLines: typeof import('./components/common/AppSkeletonLines.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HomeHeroSection: typeof import('./components/home/HomeHeroSection.vue')['default']
    HomeHighlightsSection: typeof import('./components/home/HomeHighlightsSection.vue')['default']
    HomeStorySection: typeof import('./components/home/HomeStorySection.vue')['default']
    KnowledgeArticleList: typeof import('./components/knowledge/KnowledgeArticleList.vue')['default']
    KnowledgeCategoryMenu: typeof import('./components/knowledge/KnowledgeCategoryMenu.vue')['default']
    KnowledgeTocNav: typeof import('./components/knowledge/KnowledgeTocNav.vue')['default']
    ProgressBar: typeof import('./components/common/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./components/common/SectionTitle.vue')['default']
  }
}
